export const INITIAL_ASSESSMENT_QUESTIONS = [
  "¿Te comprometes demasiado?",
  "¿Necesitas desesperadamente controlar a las mujeres, a los hombres y a las relaciones, y disimulas tus esfuerzos por controlar a la gente y las situaciones bajo la apariencia de “ser útil”?",
  "¿Te sientes demasiado responsable de los sentimientos, acciones, necesidades y bienestar de otros?",
  "¿Te enorgulleces de crear calma en una situación caótica?",
  "¿Tratas de complacer a otros y nunca a ti mismo?",
  "¿Te cuesta expresar lo que sientes?",
  "¿A veces te ves atraído hacia personas que tienen problemas por resolver o están involucradas en situaciones caóticas, inciertas y emocionalmente dolorosas?",
  "¿Tienes dificultad para divertirte?",
  "¿Creciste en medio de demasiados problemas?",
  "¿Tiendes a ignorar los problemas y pretendes que no existen?",
  "¿Creciste en una familia problemática, reprimida, disfuncional o con problemas de adicción?",
  "¿Sientes que, si no eres productivo, no vales?",
  "¿Te sientes incómodo cuando te alaban o te hacen algún cumplido?",
  "¿Te sientes atrapado en tus relaciones?",
  "¿Quisieras tener más tiempo para hacer ejercicio, tener aficiones o practicar deportes?",
  "¿Dices muy seguido que no toleras ciertas conductas de otros?",
  "¿Sientes a menudo que estás loco y te preguntas con frecuencia qué es ser normal?",
  "¿Te sientes muy ansioso ante un cambio o una promoción en el trabajo?",
  "¿Mientes o exageras cuando sería igual de fácil decir la verdad?",
  "¿Buscas constantemente afirmación y aprobación?",
  "¿Revisas las redes sociales más de 5 veces al día?",
  "¿Tienes miedo a tu propia ira?",
  "¿Buscas personas necesitadas para ayudarlas?",
  "¿Tratas de guardar tus sentimientos para ti mismo y poner buena cara?",
  "Cuando flojeas, ¿te excusas?",
  "¿Llegas siempre tarde a las citas, reuniones, etc.?",
  "¿Te sientes cansado y sin energía?",
  "¿Sientes que, si no te llevas bien con tus superiores, es tu culpa?",
  "¿No quieres asumir ningún riesgo?",
  "¿Tiendes a gastar dinero compulsivamente, comer más de lo debido, tomar tranquilizantes, trabajar, fumar o beber demasiado?",
  "¿Has perdido interés por el sexo o, por el contrario, sientes un interés excesivo y recurres con frecuencia a la pornografía, la masturbación, los videojuegos o el deporte? ¿Utilizas alguno de estos medios como forma de escape?",
  "¿Tienes frecuentes problemas médicos como colitis, úlceras, hipertensión, asma, dolores de cabeza o de espalda?",
  "¿Te accidentas frecuentemente?",
  "¿Tienes miedo al abandono, a la soledad o al rechazo?",
  "¿Crees que puedes salir adelante sin la ayuda de Dios?",
  "¿Tiendes a minimizar los problemas y a tratar de ocultarlos?",
  "¿Te encuentras constantemente culpando a otros?"
];

export const INITIAL_ASSESSMENT_OPTIONS = [
  { value: 1, label: 'Sí' },
  { value: 0, label: 'No' }
];
