export const FULL_RESPONSE_OPTIONS = [
  { value: 2, label: 'MUCHO' },
  { value: 1, label: 'POCO' },
  { value: 0, label: 'NADA' }
];

export const QUESTION_ENEATYPES = [
  3, 5, 2, 8, 4, 4, 6, 3, 9, 8, 1, 7, 2, 4,
  8, 5, 8, 2, 7, 9, 2, 2, 6, 3, 5, 6, 2, 3,
  8, 3, 8, 5, 7, 9, 1, 3, 3, 6, 7, 4, 8, 4,
  6, 1, 2, 3, 2, 1, 9, 5, 5, 7, 5, 2, 8, 4,
  4, 3, 5, 6, 7, 2, 1, 3, 4, 9, 5, 4, 1, 6,
  6, 7, 7, 7, 9, 8, 3, 1, 2, 8, 6, 4, 1, 7,
  3, 3, 3, 9, 2, 8, 8, 2, 5, 5, 7, 3, 1, 8,
  6, 7, 5, 2, 6, 8, 4, 1, 6, 1, 9, 5, 8, 1,
  1, 8, 3, 2, 7, 5, 1, 7, 9, 2, 7, 9, 5, 8,
  8, 3, 5, 4, 3, 2, 9, 5, 9
];

const RAW_QUESTIONS = [
  `Me esfuerzo por superarme cada día. Me gusta sentirme capaz y obtener reconocimiento en aquello que me propongo.`,
  `Antes de iniciar un proyecto o tarea suelo estudiarlo muy bien. Eso me genera mayor confianza y competencia y me permite perder el menor tiempo posible.`,
  `Me siento impulsado a apoyar a los demás para lograr que sean cada vez mejores.`,
  `Siempre trato de resolver las diferencias hablando pero dejando muy claros mis argumentos, mi posición y mi verdad.`,
  `Habitualmente recreo en mi imaginación situaciones con contenidos emocionales muy intensos que contrastan bastante con lo que sucede externamente.`,
  `Me atrae sobre todo lo que es inusual o fuera de lo común, llegando incluso hasta lo que es raro. Lo que a los demás puede parecerles ordinario, a mí me parece fascinante.`,
  `Cuando tengo que tomar decisiones cruciales, estudio a fondo la situación con todos sus pros y contras, y lo converso con personas importantes de mi vida, para considerar nuevos puntos de vista.`,
  `Tengo gran capacidad para obtener resultados. Me gusta sentirme activo y en movimiento.`,
  `Muchas veces pienso en hacer cosas que son necesarias para mi bienestar, pero siempre encuentro algo que me desvía hacia otras actividades más urgentes.`,
  `Soy una persona justa, fuerte, decidida e independiente. Quien pone las reglas del juego sin necesidad de caer bien o tener que demostrar nada a nadie.`,
  `Con cierta frecuencia mis amigos me comentan que debería ser menos exigente o preocupón y disfrutar un poco más.`,
  `Con frecuencia he logrado resolver situaciones muy difíciles o conflictivas gracias a mi buen sentido del humor, espontaneidad y versatilidad.`,
  `En mis relaciones afectivas suelo entregarme al 100%, pero al mismo tiempo, espero de vuelta una entrega al mismo nivel que yo.`,
  `Quiero que mi vida sea profunda, única y singular. Que se diferencie de la del resto de las personas.`,
  `Me considero una persona firme, directa y si es necesario confrontativa: voy directo al grano, sin tapujos ni rodeos.`,
  `He detectado que puedo quedarme atrapado mucho tiempo en modo de preparación, en el que no dejo de recopilar información que pueda serme de utilidad más adelante.`,
  `Cuando tengo la razón, defiendo mi postura de forma enérgica y directa.`,
  `Dar a los demás aquello que necesitan y tratarlos de manera especial, es una motivación fundamental en mi vida.`,
  `Me encanta conectar de forma creativa situaciones o temas que son muy distintos entre sí.`,
  `Sirvo de apoyo a otros para mantener la armonía de mi entorno.`,
  `Tengo una gran capacidad para detectar e identificar aquellas cosas que más le interesan y atraen a alguien más, incluso mucho antes de que el otro lo exprese abiertamente.`,
  `Para mí es fundamental la conexión que puedo lograr con las personas y el lugar especial y preponderante que ocupo en la vida de los demás.`,
  `Tiendo a ser desconfiado por naturaleza, por lo que me gusta tener siempre encendida una pequeña alerta y estar atento a lo que pudiese suceder.`,
  `Cuando me enfoco en terminar una tarea o sacar adelante un proyecto, me coloco el traje que sea necesario, hago a un lado mis cuestionamientos y me pongo manos a la obra.`,
  `En una conversación animada generalmente soy un observador y oyente callado; suelo reservar mi participación a las cuestiones significativas.`,
  `Me considero una persona realista, que tiene muy en cuenta lo que podría salir mal, aunque con frecuencia me juzguen como pesimista.`,
  `Disfruto mucho cuando consigo despertar emociones positivas en los demás, por la manera como los trato y la conexión que genero con ellos.`,
  `Tengo fuertes deseos de sobresalir pero no suelo expresarlos abiertamente; prefiero que lo que hago sea lo que hable y demuestre mi capacidad y talento.`,
  `Cuando quiero algo tomo la iniciativa y me mantengo sólido hasta conseguirlo. Disfruto las situaciones estimulantes y participar en discusiones que me permitan demostrar mi fortaleza.`,
  `Me gusta recibir reconocimiento, pero regocijarme en ello me hace sentir egoísta y temo que los demás me consideren vanidoso y se distancien de mí.`,
  `Me siento muy cómodo en el rol de líder o jefe. Soy muy protector de mi gente y ellos se sienten seguros junto a mí, porque valoran mi capacidad de hacerle frente a los desafíos que se me presentan.`,
  `Necesito en gran medida alejarme y tener mi espacio para reflexionar y digerir mis impresiones.`,
  `Me siento responsable de inyectar energía y entusiasmo en cada situación, para que las cosas no se vuelvan monótonas o aburridas.`,
  `Me es fácil mantenerme en un puesto cuando siento que aporto valor y hay armonía a mi alrededor, pudiendo postergar otros desafíos si me siento a gusto donde estoy.`,
  `Continuamente busco hacer las cosas bien. Ojalá los demás no se conformaran con hacer las cosas a medias o apenas aceptables.`,
  `Soy un experto en resaltar aquellos aspectos que más me favorecen, logrando así crear una muy buena impresión de mí ante los demás.`,
  `Para mí es natural el ir midiendo mis avances o logros, y esto me ayuda a mantener mi ritmo y energía vital.`,
  `A menudo converso con personas de confianza sobre las situaciones adversas que me tomaron por sorpresa, con el propósito de compartir lo que aprendí y evitar que les pase algo similar.`,
  `Cuando me reconozco frustrado, tiendo a moverme para generar algo positivo en el ambiente, que me motive y me cambie el chip.`,
  `Con frecuencia me descubro recreando en mi mente escenas pasadas, agregando nuevos diálogos e intentando comprender el significado de alguna frase o acto, motivo por el cual me cuesta mucho pasar página y cerrar situaciones.`,
  `Soy una persona de "Todo o Nada", no me interesa guardar las apariencias ni caerle simpático a la gente.`,
  `Siento que soy distinto y aunque trato de encajar no lo logro del todo. La mayoría de las veces tampoco quiero encajar, si eso significa ceder en aquellos aspectos que para mí son auténticos y no negociables.`,
  `En lo cotidiano no me gusta suponer, y menos improvisar. Prefiero preguntar para tener certeza de las cosas, pero qué bueno sería que existiera un manual claro y completo para todo.`,
  `Cuando algo no está bien hecho, suelo instruir o corregir a los demás, incluso sin que me lo pidan.`,
  `En mis relaciones afectivas me veo invirtiendo mucha energía y haciendo todo lo necesario para que éstas funcionen.`,
  `Me gustan los retos, porque me generan combustible para mantenerme en movimiento y enfocado. Generalmente soy impaciente con aquellos que van a un ritmo más lento.`,
  `Para mí son de vital importancia los vínculos estrechos que pueda establecer con los demás. Sentirme cercano y conectado hace que se torne mucho más amable mi vida.`,
  `Me siento tenso y ofuscado cuando una situación no se ajusta a lo correcto, y cuando lo expreso, me sorprende que los demás no deseen corregir de manera inmediata lo que está mal hecho o no funciona.`,
  `Siempre busco evitar que surjan conflictos a mi alrededor, y minimizar los que son inevitables. Para mí es importante que haya paz y armonía en el ambiente.`,
  `Soy muy buen observador, lo que me permite tener sólidos argumentos si decido opinar sobre los temas que son de mi interés.`,
  `Puedo agotarme mentalmente por completo o no conseguir concentrarme si no tengo tiempo a solas para recargarme. En estos casos las necesidades emocionales de los demás pueden presentarse como demasiado abrumadoras.`,
  `Pongo mucha energía y busco activamente llenar mi día de experiencias valiosas y gratificantes, que me mantengan entusiasmado y ocupado.`,
  `Tengo una marcada preferencia por la comprensión más que la acción y por observar más que participar. Si participo, me gusta mantenerme independiente y, en la medida de lo posible, poder gestionar mi disponibilidad.`,
  `Puedo hacer a un lado mis intereses para poner primero el bienestar de las personas más cercanas e importantes para mí.`,
  `Incluso en las situaciones más difíciles no suelo echarme para atrás, las confronto y sigo adelante.`,
  `No termino de saber por qué unos días puedo ser la persona más encantadora y amable del mundo, y otros días le encuentro "peros" a todo.`,
  `Para mí es muy importante poder expresarme y dejar una huella personal en lo que hago. Que cuando yo no esté, se note que pasé por ahí.`,
  `Soy una persona a la que le gusta ir directo a la acción y encontrar soluciones que se puedan aplicar de forma inmediata y práctica. Amo la eficiencia.`,
  `En general soy moderado en la comunicación y aunque tengo un mundo interno muy vasto, tiendo a controlarme en la expresión de lo que siento y ser reservado en lo que comunico.`,
  `A diario, o de manera muy frecuente, me preocupo de cuál será mi futuro en unos meses, unos años y, sobre todo, en mi vejez.`,
  `En muchas ocasiones consigo encontrar soluciones inesperadas y de último momento, eso algunos lo llaman "suerte", yo lo llamo conexión de múltiples ideas o "encender la chispa".`,
  `Uno de mis grandes valores es la capacidad que tengo para el compromiso en las relaciones que establezco y la habilidad de escuchar a las personas y hacerles sentir bien.`,
  `Siempre actúo de acuerdo a lo que yo considero correcto o bueno, y no según lo que creen o piensan los demás.`,
  `Algunas elecciones y decisiones importantes tomadas en mi vida, han buscado obtener la valoración y reconocimiento de mi entorno.`,
  `Hablar respecto a cómo siento y pienso es una de mis conversaciones favoritas, aunque a veces me excedo, con el fin de llegar a ser comprendido.`,
  `Los ambientes conflictivos me generan ansiedad y no entiendo por qué las personas no ceden más en sus intereses personales para poder sentirnos todos bien.`,
  `De aquellos temas que me atraen, me interesa adquirir la mayor cantidad posible de información hasta desarrollar mis propios conceptos y sacar mis propias conclusiones.`,
  `Pierdo fácilmente el interés en las cosas o relaciones que me parecen poco trascendentes, comunes o que tengo al alcance de la mano.`,
  `Considero que el reconocimiento propio o ajeno es bien merecido cuando uno se acerca a la excelencia. Hacer las cosas simplemente "bien" es apenas aceptable.`,
  `Soy un miembro leal y estable de mis grupos y asociaciones. Ahí, donde participo, prefiero lineamientos y estatutos claros y mantenerme atento a que quien lidere sea confiable.`,
  `Saber cómo se hacen las cosas, ya sea en el trabajo, en un juego de mesa, o cuando hay una enfermedad, es vital para mí, ya que de lo contrario me quedaría paralizado.`,
  `Mi mente no para de funcionar, saltando de una idea a otra e imaginando incluso situaciones extraordinarias, que me llevan a pensar que todo puede estar de alguna forma relacionado.`,
  `Tengo una gran habilidad y destreza mental para ligar diversas soluciones a situaciones complejas, saltando de un tema a otro con tanta facilidad, como un simio se cambia de rama en un árbol.`,
  `Si no encuentro suficientes estímulos agradables en el ambiente, paso rápidamente a otra actividad o me voy a otro lugar.`,
  `De forma natural presto atención al bienestar del grupo y antepongo las necesidades externas a las internas.`,
  `Me gustan las cosas claras. Si en una conversación detecto omisiones o falta de claridad, soy contundente y presiono hasta que se muestran los verdaderos intereses ocultos.`,
  `Es muy importante para mí proyectar siempre una buena imagen en el lugar donde estoy.`,
  `Siempre hay una forma correcta de hacer las cosas: perfectas y como deben hacerse, más allá de los gustos y de las preferencias personales.`,
  `En las relaciones el mayor egoísmo se demuestra por la falta de gratitud o consideración de lo que uno ha hecho por el otro.`,
  `Dada mi firmeza y franqueza, en muchas ocasiones casi sin proponérmelo, suelo intimidar a las personas que me rodean.`,
  `Cuando he tomado decisiones difíciles, aunque haya obtenido un resultado positivo, reflexiono mucho respecto a si pude haberme preparado mejor o si fui demasiado impulsivo ante una decisión que implicaba tanto.`,
  `Cuando algo me incomoda, me doy cuenta por mis sensaciones corporales, pero usualmente suelo ignorarlas. Después, imagino conversaciones en las que expreso aquello que me incomodó.`,
  `Nadie llega a ser tan severo y crítico como lo soy conmigo mismo, por eso me siento agobiado cuando me equivoco y me cuesta mucho simplemente dejarlo ir.`,
  `Encuentro excitantes los proyectos donde tengo posibilidad de explorar soluciones diversas; incluso sobre la marcha, usualmente se me ocurren nuevas ideas que complementan el plan inicial o le dan un giro inesperado.`,
  `Hay veces que no expreso completamente la verdad sobre mí, sino lo que me gustaría que hubiese sido.`,
  `No basta con ser bueno. Me gusta tener metas claras y saber en qué lugar del camino me encuentro para continuar trabajando en ser la mejor versión de mí mismo.`,
  `Soy un buen vendedor de mí mismo y sé cómo convencer a los demás.`,
  `Cuando no quiero hacer algo o algo no me interesa, únicamente me moviliza a hacerlo el hecho de evitar una posible discusión o conflicto.`,
  `Me caracterizo por ser una persona generosa con su tiempo y atención cuando alguien me necesita, y aunque en ocasiones llego a terminar agotado emocionalmente, suele valer la pena por apoyar a alguien más.`,
  `No tolero el abuso o la injusticia a los más vulnerables. En esos casos actúo para equilibrar las cosas.`,
  `Protejo de forma apasionada a quienes se encuentran bajo mi tutela, siendo extremadamente territorial, aunque mantengo en estricta privacidad lo que siento por las personas que me rodean.`,
  `Cuando una persona que aprecio se encuentra en dificultades, a menudo tomo el rol de apoyo, escucha y soporte, al grado de que muchas veces hago míos sus problemas.`,
  `Reconozco que me cuesta, pero me gustaría ser más sociable o expresivo con aquellos que me rodean, sobre todo con las personas más cercanas y allegadas a mí.`,
  `Disfruto adentrarme con total profundidad en aquellos temas que me interesan, logrando extraer conclusiones e ideas que aporten un nuevo enfoque a lo que hasta entonces se conocía.`,
  `Mientras me encuentro en un sitio, tengo mucha facilidad para crear un buen ambiente, usando mi espontaneidad, simpatía y sentido del humor.`,
  `A menudo logro obtener la atención del otro debido a que conozco bien los aspectos que más me favorecen.`,
  `Difícilmente me encuentro satisfecho con lo que hago; tengo un juez interno muy activo que me insta a hacerlo siempre mejor.`,
  `Tengo una gran capacidad para mantenerme autónomo e independiente.`,
  `Las rutinas y hábitos me dan seguridad y paz, tener que modificarlos me genera un conflicto interno que a veces es difícil de comprender por parte de los demás.`,
  `Me siento en el mundo como si fuese el invitado a un gran banquete, es decir un lugar donde existen siempre infinitas posibilidades de conocer, explorar y disfrutar.`,
  `En mis relaciones suelo cambiar entre momentos de mucha cercanía y otros donde necesito separarme mucho para poder recargarme en solitario.`,
  `Tengo muy desarrollada la capacidad para crear conexiones con las personas, incluso desde un primer encuentro o acercamiento.`,
  `Puedo detectar muchas de las incongruencias y falsedades de las personas y, a veces, se las hago notar a través de comentarios humorísticos pero certeros.`,
  `Fácilmente me doy cuenta de las fortalezas, debilidades y poder que tienen los demás.`,
  `Aprecio mucho la originalidad y la sensibilidad, y trato de manifestarlas sutilmente en los temas de los que hablo, en lo que pienso y en lo que expresa mi forma de ser.`,
  `Soy muy autoexigente y siempre que cometo fallos, me fastidia tanto que me impide poder disfrutar o valorar todo lo que sí he logrado hacer bien.`,
  `Mi mente tiene un gran capacidad para detectar todo aquello que podría salir mal, fallar o no funcionar.`,
  `Me encuentro continuamente orientado hacia la superación y por ello la más mínima falla suele ponerme de mal humor.`,
  `Muchas veces, cuando identifico una necesidad o deseo propio que puede confrontar al prójimo, tiendo a quitármelo de la cabeza, realizando otro tipo de actividades en beneficio común o incluso ajeno.`,
  `Usualmente me muestro muy reservado, sin embargo con algunas pocas personas suelo mostrarme muy abierto e incluso cómico y gracioso. Me encanta hacer reír con salidas irreverentes.`,
  `Soy firme a la hora de expresar y defender mis ideas, incluso en los entornos más difíciles, logrando mantener mi posición a pesar de las resistencias que se presenten. Algunas veces mi contundencia es entendida como prepotencia, intolerancia y arrogancia.`,
  `Antes de relajarme necesito primero haber cumplido con mis responsabilidades o deberes.`,
  `Me pregunto por qué no se acepta más a menudo que, en muchas de las cosas, el mundo estaba mejor en otros tiempos pasados.`,
  `Me gusta expresar mi voluntad, ser mi propia autoridad y mantener el control de las situaciones. En algunas ocasiones me pueden tachar de inconformista e individualista.`,
  `Suelo aprovechar las oportunidades que se me presentan para alcanzar mis metas y lograr mis propósitos.`,
  `Me involucro activamente cuando alguien tiene problemas, dándole fuerzas para superarlos u ofreciéndole mi apoyo, cercanía y empatía.`,
  `Mi deseo de pensar positivamente es un enganche muy poderoso que reencuadra las cosas de manera automática hacia el lado más luminoso.`,
  `En mis relaciones afectivas requiero de mucho espacio y que se respete, por encima de todo, mi privacidad y mi tiempo.`,
  `Apoyo a las personas que lo necesitan y lo solicitan. Estoy a favor de que todos estemos en igualdad de condiciones.`,
  `Más que seguir los pasos de manera secuencial, me gusta explorar en mi mente ideas poco convencionales para lograr el resultado deseado.`,
  `Me identifico con los diferentes enfoques que forman parte de un conflicto y por ello se me da bien mediar entre ellos. Lo que me cuesta es ver y defender lo que realmente me interesa a mí.`,
  `Puedo darme cuenta con mucha facilidad de las cosas que le harían sentir bien a alguien, a veces incluso mucho mejor que la propia persona.`,
  `Me doy cuenta que los demás disfrutan mucho de mi compañía, porque siempre inyecto energía positiva e ingeniosa en los ambientes rutinarios, facilitando el enfoque hacia objetivos compartidos.`,
  `Detesto las solicitudes y las imposiciones que alteren mi rutina diaria o las actividades que ya tenía planificadas.`,
  `Mi capacidad de abstraerme y concentrarme en aquello que me interesa, me permite crear una burbuja mental a mi alrededor en la que puedo sumergirme por largos periodos, desapareciendo en ese momento el resto del mundo que me rodea.`,
  `Tengo claro lo que deseo y sobre todo lo que no, por lo que no tengo problema alguno en ejecutar cambios a mi alrededor hasta lograr que las cosas vayan en la dirección que deseo.`,
  `Tengo un radar interno bien desarrollado, el cual me permite reconocer el nivel de fuerza de alguien más y determinar si está de mi lado o no.`,
  `Cuando algo falla y no obtengo el éxito o el reconocimiento esperado, resulta devastador para mí y me toma tiempo el superarlo aunque no lo demuestro.`,
  `A pesar de ser incluido en un grupo, tiendo a marcar una distancia con los demás, ya sea física, emocional o intelectual.`,
  `De manera constante mantengo diálogos internos muy intensos, en los que busco dar respuesta a situaciones que me han afectado emocionalmente.`,
  `La presentación de uno mismo es tan importante como lo que hay detrás, por lo que me preocupo en proyectar una imagen adecuada.`,
  `Muchas veces la gente me busca como alguien que les aporte comprensión empática, escucha o un espacio donde se sienten "a salvo".`,
  `Soy muy flexible a la hora de ceder en situaciones y en lo que quieren los demás, aunque a veces sienta que traiciono un poco mis verdaderos deseos.`,
  `Soy muy reservado, distante y muy selectivo a la hora de incluir personas en mi mundo o en mi espacio privado.`,
  `La confrontación me desgasta y suelo evitarla cambiando de tema o haciendo como que no existe, prefiero buscar una alternativa que no pase por la confrontación, aunque tenga que renunciar a cosas importantes para mí.`
];

export const FULL_STATEMENTS = RAW_QUESTIONS.map((text, index) => {
  const order = index + 1;
  const blockRanges = [
    [1, 14, 'B01'],
    [15, 28, 'B02'],
    [29, 42, 'B03'],
    [43, 56, 'B04'],
    [57, 70, 'B05'],
    [71, 83, 'B06'],
    [84, 96, 'B07'],
    [97, 109, 'B08'],
    [110, 122, 'B09'],
    [123, 135, 'B10']
  ];
  const block = blockRanges.find(([start, end]) => order >= start && order <= end)?.[2] || 'B10';
  return {
    id: `P${String(order).padStart(3, '0')}`,
    order,
    block,
    text,
    eneatype: QUESTION_ENEATYPES[index]
  };
});

export const FULL_BLOCKS = [
  { id: 'B01', title: 'Bloque 1', start: 1, end: 14 },
  { id: 'B02', title: 'Bloque 2', start: 15, end: 28 },
  { id: 'B03', title: 'Bloque 3', start: 29, end: 42 },
  { id: 'B04', title: 'Bloque 4', start: 43, end: 56 },
  { id: 'B05', title: 'Bloque 5', start: 57, end: 70 },
  { id: 'B06', title: 'Bloque 6', start: 71, end: 83 },
  { id: 'B07', title: 'Bloque 7', start: 84, end: 96 },
  { id: 'B08', title: 'Bloque 8', start: 97, end: 109 },
  { id: 'B09', title: 'Bloque 9', start: 110, end: 122 },
  { id: 'B10', title: 'Bloque 10', start: 123, end: 135 }
];

export const FULL_TYPE_DISTRIBUTION = QUESTION_ENEATYPES.reduce((acc, eneatype) => {
  acc[eneatype] = (acc[eneatype] || 0) + 1;
  return acc;
}, { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0 });
